import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";

export const metadata: Metadata = {
  title: "Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <link rel="icon" href="/favicon-light.ico" media="(prefers-color-scheme: light)" />
      <link rel="icon" href="/favicon-dark.ico" media="(prefers-color-scheme: dark)" />
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
          <Toaster position="top-right" theme="system" swipeDirections={["right", "left", "top", "bottom"]} closeButton />
        </ThemeProvider>
      </body>
    </html>
  );
}
